### ISSUE TITLE
Request for additional docs on Addresses

### ISSUE THREAD

**Issue by rootulp** [FuelLabs/fuel-docs#75]
I just read this doc on [Addresses](https://docs.fuel.sh/v1.1.0/Concepts/Data%20Structures/Addresses.html#addresses) and I'm wondering if someone can please point me to docs on how the Fuel address registry works? If an address isn't registered, is a 20 byte address used? If so, why does an address on testnet-beta-1 [block explorer](https://fuellabs.github.io/block-explorer-v2/address/fuel1fdvs496nqjdapke85nnl9cl8jdnk5sl35cegslmv2mxs5fnvfg8qy5tan0) use an address that contains 255 binary digits (so more than 20 bytes)?

**Comment by adlerjohn** [comment]
The linked Addresses is for Fuel v1, and thus probably isn't relevant.

**Comment by rootulp** [comment]
Thanks for pointing that out. For clarification, does that mean Fuel v2 uses 32 byte addresses? I'm inferring based on the block explorer link.
